sudo: required

env:
  - DOCKERHUB_IMAGE: $DOCKERHUB_USERNAME/meteor-clock:$TRAVIS_BRANCH
  - DOCKERHUB_IMAGE_LATEST: $DOCKERHUB_USERNAME/meteor-clock:latest

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - curl https://install.meteor.com/ | sh

script:
  - ./add_buildinfo.sh
  - meteor build --directory meteor_build
  - docker build --tag $DOCKERHUB_IMAGE .

after_success:
  - docker login --username="$DOCKERHUB_USERNAME" --password="$DOCKERHUB_PASSWORD"
  - docker push $DOCKERHUB_IMAGE
  - docker tag $DOCKERHUB_IMAGE $DOCKERHUB_IMAGE_LATEST
  - docker push $DOCKERHUB_IMAGE_LATEST